<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DocumentarEnvio extends Model
{
    //
    protected $table = 'documentar_envios';
    protected $fillable = ['
    REFERENCIA',
    'NUMERO_ENVIO',
    'CODIGO_ADMISION',
    'NUMERO_BULTOS',
    'CLIENTE_REMITENTE',
    'CENTRO_REMITENTE',
    'NIF_REMITENTE',
    'NOMBRE_REMITENTE',
    'DIRECCION_REMITENTE',
    'PAIS_REMITENTE',
    'CODIGO_POSTAL_REMITENTE',
    'POBLACION_REMITENTE',
    'PERSONA_CONTACTO_REMITENTE',
    'TELEFONO_CONTACTO_REMITENTE',
    'EMAIL_REMITENTE',
    'NIF_DESTINATARIO',
    'NOMBRE_DESTINATARIO',
    'DIRECCION_DESTINATARIO',
    'PAIS_DESTINATARIO',
    'CODIGO_POSTAL_DESTINATARIO',
    'POBLACION_DESTINATARIO',
    'PERSONA_CONTACTO_DESTINATARIO',
    'TELEFONO_CONTACTO_DESTINATARIO',
    'EMAIL_DESTINATARIO',
    'CODIGO_PRODUCTO_SERVICIO',
    'KILOS',
    'VOLUMEN',
    'CLIENTE_REFERENCIA',
    'IMPORTE_REEMBOLSO',
    'IMPORTE_VALOR_DECLARADO',
    'TIPO_PORTES',
    'OBSERVACIONES1',
    'OBSERVACIONES2',
    'TIPO_MERCANCIA',
    'VALOR_MERCANCIA',
    'MERCANCIA_ESPECIAL',
    'GRANDES_SUPERFICIES',
    'PLAZO_GARANTIZADO',
    'LOCALIZADOR',
    'NUM_PALETS',
    'FECHA_ENTREGA_APLAZADA',
    'ENTREGA_APLAZADA',
    'TIPOS_DOCUMENTO',
    'TIPOS_DOCUMENTO_REFERENCIA',
    'GESTION_DEVOLUCION_CONFORME',
    'ENVIO_CON_RECOGIDA',
    'IMPRIMIR_ETIQUETA',
    'ETIQUETA64',
    'UBICACION_ETIQUETA',
    'ENVIO_DEFINITIVO',
    'TIPO_FORMATO'
    ];

    protected $guarded = ['id'];


}
